music_area:
  spawn:
    world: world
    x: -17454.0
    y: 68.0
    z: -235397.0
    radius: 180.0
    sound_key: "black_clover"
    volume: 0.05
  loja:
    world: world
    x: -17672.0
    y: 81.0
    z: -235916.0
    radius: 50.0
    sound_key: "infinity"
    volume: 0.05

